export const batchDataImport = [
  {
    vch: '255',
    date: '2026-04-23',
    product: 'TOTAL CARE PLUS FC LEMON 1 LTR',
    type: 'Liquid',
    quantity_per_batch: 25,
    unit: 'LTR',
    description: 'Phenolic based liquid cleaner - Lemon fragrance',
    raw_materials: [
      { name: 'D.M. WATER', qty: 24, unit: 'LTR' },
      { name: '2L', qty: 0.75, unit: 'KGS' },
      { name: 'LEMON SPLASH (SENT)', qty: 0.375, unit: 'KGS' },
      { name: '13L', qty: 0.75, unit: 'KGS' },
      { name: '1 LIT PHENYLE BOTTLE', qty: 25, unit: 'PCS' },
      { name: 'STICKERS TOTAL CARE PLUS FC LEMON 1 LTR', qty: 25, unit: 'PCS' },
      { name: 'CAP (PCO) WHITE', qty: 25, unit: 'PCS' },
      { name: 'BOX FOR 12 NOS', qty: 2, unit: 'PCS' },
    ],
  },
  {
    vch: '256',
    date: '2026-04-23',
    product: 'TOTAL CARE PLUS FC MOGRA 1 LTR',
    type: 'Liquid',
    quantity_per_batch: 25,
    unit: 'LTR',
    description: 'Phenolic based liquid cleaner - Jasmine fragrance',
    raw_materials: [
      { name: 'D.M. WATER', qty: 24, unit: 'LTR' },
      { name: '2L', qty: 0.75, unit: 'KGS' },
      { name: 'MADURAI JASMIN COV', qty: 0.25, unit: 'KGS' },
      { name: '13L', qty: 0.75, unit: 'KGS' },
      { name: '16L', qty: 0.1, unit: 'KGS' },
      { name: '1 LIT PHENYLE BOTTLE', qty: 25, unit: 'PCS' },
      { name: 'WHITE CAP (PCO)', qty: 25, unit: 'PCS' },
      { name: 'BOX FOR 12 NOS', qty: 2, unit: 'PCS' },
    ],
  },
  {
    vch: '257',
    date: '2026-04-23',
    product: 'B5 LOOSE DETERGENT',
    type: 'Powder',
    quantity_per_batch: 400,
    unit: 'KGS',
    description: 'Premium loose detergent powder',
    raw_materials: [
      { name: 'SODA', qty: 90, unit: 'KGS' },
      { name: '5L', qty: 12, unit: 'KGS' },
      { name: '1 NO', qty: 30, unit: 'KGS' },
      { name: 'CBX', qty: 0.1, unit: 'KGS' },
      { name: 'SALT', qty: 210, unit: 'KGS' },
      { name: '26 No Sent (OXYBLUE)', qty: 0.8, unit: 'KGS' },
      { name: 'GREEN SPECKLES', qty: 3, unit: 'KGS' },
      { name: 'NILA SEV', qty: 2, unit: 'KGS' },
      { name: 'BLUE SPECKLES', qty: 2, unit: 'KGS' },
      { name: 'ORANGE SPECKLES', qty: 3, unit: 'KGS' },
      { name: 'BARIK POWDER', qty: 8, unit: 'KGS' },
      { name: 'BAG 25 KG PACKING', qty: 16, unit: 'PCS' },
      { name: 'SS (SODIUM SULPHATE)', qty: 20, unit: 'KGS' },
      { name: '7L', qty: 4, unit: 'KGS' },
    ],
  },
  {
    vch: '258',
    date: '2026-04-23',
    product: 'B-5 5KGS',
    type: 'Powder',
    quantity_per_batch: 45,
    unit: 'PCS',
    description: 'Detergent powder in 5kg pouches',
    raw_materials: [
      { name: 'B5 LOOSE DETERGENT', qty: 225, unit: 'KGS' },
      { name: 'BAG TUKDA', qty: 9, unit: 'PCS' },
      { name: '5 KGS PLAIN POUCH', qty: 45, unit: 'PCS' },
    ],
  },
  {
    vch: '261',
    date: '2026-04-23',
    product: 'A4 LOOSE DETERGENT POWDER',
    type: 'Powder',
    quantity_per_batch: 200,
    unit: 'KGS',
    description: 'Standard loose detergent powder',
    raw_materials: [
      { name: 'SALT', qty: 128, unit: 'KGS' },
      { name: 'SODA', qty: 25, unit: 'KGS' },
      { name: '5L', qty: 6, unit: 'KGS' },
      { name: '1 NO', qty: 14, unit: 'KGS' },
      { name: 'GREEN SPECKLES', qty: 1.5, unit: 'KGS' },
      { name: 'BLUE SPECKLES', qty: 3, unit: 'KGS' },
      { name: 'BAG 25 KG PACKING', qty: 8, unit: 'PCS' },
      { name: 'MULTI MOGRA (SENT)', qty: 0.3, unit: 'KGS' },
      { name: 'DOLOMITE', qty: 20, unit: 'KGS' },
      { name: 'BARIK POWDER', qty: 4, unit: 'KGS' },
    ],
  },
  {
    vch: '264',
    date: '2026-04-23',
    product: 'MPL-2',
    type: 'Powder',
    quantity_per_batch: 200,
    unit: 'KGS',
    description: 'Multi-purpose loose detergent variant 2',
    raw_materials: [
      { name: 'SALT', qty: 128, unit: 'KGS' },
      { name: 'SODA', qty: 25, unit: 'KGS' },
      { name: '1 NO', qty: 10, unit: 'KGS' },
      { name: '5L', qty: 5, unit: 'KGS' },
      { name: 'DOLOMITE', qty: 30, unit: 'KGS' },
      { name: 'DIPHENYL OXIDE (NLP)', qty: 0.1, unit: 'KGS' },
      { name: 'MULTI MOGRA (SENT)', qty: 0.2, unit: 'KGS' },
      { name: 'BLUE SPECKLES', qty: 1.5, unit: 'KGS' },
      { name: 'GREEN SPECKLES', qty: 1.5, unit: 'KGS' },
      { name: 'ORANGE SPECKLES', qty: 1.5, unit: 'KGS' },
      { name: 'BAG 25 KG PACKING', qty: 8, unit: 'PCS' },
    ],
  },
  {
    vch: '265',
    date: '2026-04-23',
    product: 'HP-1',
    type: 'Powder',
    quantity_per_batch: 200,
    unit: 'KGS',
    description: 'Heavy-duty premium detergent powder',
    raw_materials: [
      { name: 'SALT', qty: 140, unit: 'KGS' },
      { name: 'SODA', qty: 15, unit: 'KGS' },
      { name: '5L', qty: 4, unit: 'KGS' },
      { name: 'CAUSTIC', qty: 2, unit: 'KGS' },
      { name: 'LEMON SQUEEZY', qty: 0.2, unit: 'KGS' },
      { name: 'BAG 25 KG PACKING', qty: 8, unit: 'PCS' },
      { name: 'BLUE SPECKLES', qty: 1.5, unit: 'KGS' },
      { name: 'GREEN SPECKLES', qty: 1.5, unit: 'KGS' },
      { name: 'ORANGE SPECKLES', qty: 1.5, unit: 'KGS' },
      { name: '1 NO', qty: 5, unit: 'KGS' },
      { name: 'DOLOMITE', qty: 30, unit: 'KGS' },
    ],
  },
  {
    vch: '263',
    date: '2026-04-23',
    product: 'ASS-3',
    type: 'Powder',
    quantity_per_batch: 200,
    unit: 'KGS',
    description: 'Advance soap substitute detergent',
    raw_materials: [
      { name: 'SALT', qty: 125, unit: 'KGS' },
      { name: 'SODA', qty: 20, unit: 'KGS' },
      { name: '1 NO', qty: 10, unit: 'KGS' },
      { name: '5L', qty: 3, unit: 'KGS' },
      { name: 'DOLOMITE', qty: 40, unit: 'KGS' },
      { name: 'LEMON SQUEEZY', qty: 0.25, unit: 'KGS' },
      { name: 'GREEN SPECKLES', qty: 2, unit: 'KGS' },
      { name: 'ORANGE SPECKLES', qty: 2, unit: 'KGS' },
      { name: 'BAG 25 KG PACKING', qty: 8, unit: 'PCS' },
    ],
  },
];
